# Generated by Django 3.0.3 on 2020-03-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_blog', '0004_rubric_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodaySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=10, verbose_name='Предмет')),
                ('lessonType', models.CharField(max_length=10)),
                ('startLessonTime', models.DateTimeField()),
                ('endLessonTime', models.DateTimeField()),
                ('auditory', models.CharField(max_length=10)),
                ('employee', models.CharField(max_length=40, verbose_name='Преподаватель')),
                ('note', models.CharField(blank=True, default='', max_length=70)),
            ],
            options={
                'verbose_name': 'Пара',
                'verbose_name_plural': 'Пары',
            },
        ),
    ]
