# Generated by Django 3.0.3 on 2020-03-24 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sh_blog', '0009_auto_20200324_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='sh_blog.UserProfile'),
        ),
    ]
