# Generated by Django 3.0.3 on 2020-03-24 11:59

from django.db import migrations, models
import sh_blog.models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_blog', '0012_auto_20200324_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=sh_blog.models.user_profile_media_path),
        ),
    ]
