# Generated by Django 3.0.3 on 2020-03-24 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sh_blog', '0013_auto_20200324_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sh_blog.UserProfile'),
        ),
    ]
