# Generated by Django 3.0 on 2020-04-02 15:13

from django.db import migrations, models
import sh_blog.models


class Migration(migrations.Migration):

    dependencies = [
        ('sh_blog', '0014_auto_20200324_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayschedule',
            name='note',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='no-avatar-300x300.jpg', upload_to=sh_blog.models.user_profile_media_path),
        ),
    ]
